"""Signal 1: LLM-based holistic classification ("vibe check").

This signal hands the full text to a Groq-hosted LLM and asks it to judge,
holistically, how likely the text is to be AI-generated. It captures the
fuzzy, gestalt qualities of AI writing (tone, structure, "feel") that are
hard to express as explicit numeric heuristics. We ask the model to return a
calibrated probability plus a short rationale rather than a yes/no, so its
output can feed the confidence scorer downstream.

The function takes an injectable ``client`` so it can be unit-tested without
hitting the network.
"""

from __future__ import annotations

import json
import os
from typing import Any, Optional

from provenanceguard.signals import SignalResult

SIGNAL_NAME = "llm_classifier"

# Default Groq model. Kept here so it is easy to swap centrally.
DEFAULT_MODEL = "llama-3.3-70b-versatile"

# Score returned when the signal cannot produce a real judgment. 0.5 = maximal
# uncertainty, so a broken signal pulls the final score toward "uncertain"
# rather than falsely toward human or AI.
NEUTRAL_FALLBACK = 0.5

_SYSTEM_PROMPT = (
    "You are a forensic text-attribution analyst. You judge whether a piece "
    "of writing was generated by a large language model or written by a human. "
    "Base your judgment on holistic qualities: voice, specificity, emotional "
    "texture, structural predictability, and idiosyncrasy. Human writing tends "
    "to be more idiosyncratic and uneven; AI writing tends to be smoother and "
    "more generic. Respond ONLY with a JSON object of the form "
    '{"ai_probability": <float 0..1>, "reasoning": "<one or two sentences>"} '
    "where ai_probability is your calibrated probability that the text is "
    "AI-generated. Do not include any text outside the JSON object."
)

_USER_TEMPLATE = "Analyze the following text:\n\n---\n{text}\n---"


def _build_client(api_key: Optional[str]):
    """Construct a Groq client. Imported lazily so tests that inject a fake
    client never require the real SDK or an API key."""
    from groq import Groq

    key = api_key or os.environ.get("GROQ_API_KEY")
    if not key:
        raise RuntimeError(
            "GROQ_API_KEY is not set; pass api_key= or set the environment variable."
        )
    return Groq(api_key=key)


def _parse_response(content: str) -> tuple[float, str]:
    """Extract (ai_probability, reasoning) from the model's JSON content.

    Raises ValueError if the payload is missing or malformed so the caller can
    fall back to a neutral score.
    """
    data = json.loads(content)
    if "ai_probability" not in data:
        raise ValueError("response JSON missing 'ai_probability'")
    prob = float(data["ai_probability"])
    reasoning = str(data.get("reasoning", "")).strip()
    return prob, reasoning


def classify_with_llm(
    text: str,
    *,
    client: Any = None,
    api_key: Optional[str] = None,
    model: str = DEFAULT_MODEL,
) -> SignalResult:
    """Run the LLM vibe-check signal over ``text``.

    Args:
        text: The content to analyze.
        client: Optional pre-built Groq-compatible client (must expose
            ``chat.completions.create``). Injected in tests; built on demand
            in production.
        api_key: Optional Groq API key. Falls back to ``GROQ_API_KEY`` env var.
        model: Groq model id to use.

    Returns:
        SignalResult with ``score`` = P(AI-generated). On any failure the
        result has ``ok=False`` and ``score`` = NEUTRAL_FALLBACK.
    """
    if not text or not text.strip():
        return SignalResult(
            name=SIGNAL_NAME,
            score=NEUTRAL_FALLBACK,
            reasoning="Empty input; cannot classify.",
            ok=False,
        )

    try:
        if client is None:
            client = _build_client(api_key)

        completion = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        content = completion.choices[0].message.content
        prob, reasoning = _parse_response(content)

        return SignalResult(
            name=SIGNAL_NAME,
            score=prob,
            reasoning=reasoning or "LLM holistic judgment.",
            details={"model": model, "raw": content},
        )
    except Exception as exc:  # noqa: BLE001 - degrade gracefully on any failure
        return SignalResult(
            name=SIGNAL_NAME,
            score=NEUTRAL_FALLBACK,
            reasoning=f"LLM signal unavailable: {exc}",
            details={"error": str(exc), "model": model},
            ok=False,
        )
